inherit_from: .rubocop_todo.yml

require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  Include:
    - lib/**/*.rb

  Exclude:
    - .gitignore
    - .rspec
    - .rubocop.yml
    - .travis.yml

    - Gemfile.lock
    - History.markdown
    - LICENSE.txt
    - README.md

    - script/**/*
    - vendor/**/*

Layout/LineLength:
  Exclude:
    - spec/**/*
    - jekyll-seo-tag.gemspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*
